baseurl: /Dynamic-Image-Resize

title: Dynamic Image Resize
description: On demand image resizing
year: 2013
author:
    name: Franz Josef Kaiser
    email: wecodemore@gmail.com
    links:
          - title: Blog
            url: http://unserkaiser.com
          - title: GitHub
            url: https://github.com/franz-josef-kaiser
          - title: Twitter
            url: https://twitter.com/unserkaiser
          - title: Google+
            url: https://plus.google.com/107110219316412982437