baseurl: /Dynamic-Image-Resize

relative_permalinks: true
permalink: /:title
pygments: true

title: 'Dynamic Image Resize'
description: 'On demand image resizing'
year: 2013
author:
    name: Franz Josef Kaiser
    email: wecodemore@gmail.com
    links:
          - title: 'Blog'
            url: http://unserkaiser.com
          - title: 'GitHub'
            url: https://github.com/franz-josef-kaiser
          - title: 'Twitter'
            url: https://twitter.com/unserkaiser
          - title: 'Google+'
            url: https://plus.google.com/107110219316412982437

navigation:
      - text: '&laquo; Home'
        title: 'Back to home page'
        url: /index.html
      - text: 'Intro'
        title: 'An introduction to the plugin'
        url: /intro/intro.html
      - text: 'Install'
        title: 'Introduction to the different way on how to install the plugin'
        url: /install/install.html
        subitems:
            - text: 'FTP'
              title: 'Upload via FTP'
              url: install/install-upload.html
            - text: 'ZIP'
              title: 'Upload Ziball to the the admin UI'
              url: install/install-zip.html
            - text: 'Git'
              title: 'The power of version control: Git'
              url: install/install-git.html
            - text: 'Composer'
              title: 'The magic of composing projects'
              url: install/install-composer.html
      - text: 'Uninstall'
        title: 'If you really need to'
        url: /uninstall/uninstall.html
      - text: 'License'
        title: 'Want to know what you are allowed to do?'
        url: /license/license.html
      - text: 'How To'
        title: 'Use the software the right way'
        url: /howto/howto.html